apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
data:
  mongodb.conf: |
    # MongoDB configuration file
    storage:
      dbPath: /data/db
      journal:
        enabled: true
    net:
      bindIp: 0.0.0.0
      port: 27017
