apiVersion: apps/v1
kind: Deployment
metadata:
  name: pritunl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pritunl
  template:
    metadata:
      labels:
        app: pritunl
    spec:
      containers:
      - name: pritunl
        image: jippi/pritunl
        ports:
        - containerPort: 80
        - containerPort: 443  
        volumeMounts:
        - name: pritunl-data
          mountPath: /data
      volumes:
      - name: pritunl-data
        persistentVolumeClaim:
          claimName: pvc-pritunl
