apiVersion: v1
kind: Service
metadata:
  name: pritunl
spec:
  type: NodePort
  selector:
    app: pritunl
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
   
